CTS_ATTRIBUTES = ['AGE','FNLWGT','EDUCATION_NUM','CAPITAL_GAIN','CAPITAL_LOSS','HOURS_PER_WEEK']
ENUM_ATTRIBUTES = {'WORKCLASS':7, 'EDUCATION':15,'MARITAL_STATUS':6,'OCCUPATION':14,'RELATIONSHIP':5,'RACE':4,'SEX':1,'NATIVE_COUNTRY':40}
ALL_ATTRIBUTES = CTS_ATTRIBUTES + list(ENUM_ATTRIBUTES.keys())